### ISSUE TITLE
undetected_chromedriver.v2

### ISSUE THREAD

**Issue by Raulbarossi** [JDaniloC/BetBot#28]
Boa tarde, como vai?

Quando tento rodar o main.py recebo esse erro
`ModuleNotFoundError: No module named 'undetected_chromedriver.v2`

ai retirar o v.2 em widgets.py o sistema aparentemente roda normal, o terminal não fecha, mas não abre a janela, estou usando WSL2, acreditar ter algo a ver? tem alguma dica para tal?

![image](https://github.com/JDaniloC/BetBot/assets/15141367/ecc81dde-53f7-4c49-b9e0-2ac1061ef35e)
o resultado, já retirei a linha MongoDB.cadastrar(usuario, senha) # Nome do usuário da conta da Bet e sua senha do database.py (comentei, na vdd) e ao entrar no mongo percebi que havia criado os dados de usuário lá.

Acredito que nesse momento a janela deveria abrir e não sei se não abre por estar usando WSL2

**Comment by JDaniloC** [comment]
Se seu WSL estiver atualizado, se não em engano agora é possível abrir janelas pelo WSL, mas se você está duvidando do WSL basta rodar direto no windows e relatar aqui ;)

**Comment by Raulbarossi** [comment]
Eu tava apanhando um tanto pra tentar rodar pyenv e conseguir a versão correta do windows, ai parti para o wsl pq achei q seria mais fácil com asdf, foi, porém to apanhando agr pq não sei se ta funcionando ou não haha, como fica seu terminal quando você executa?

eu instalei o pyenv aqui no windows e desinstalei o python direto, mas qnd rodo python no terminal sou direcionado para a microsoft store, acho q vou tentar asdf pra windows e ver oq acontece haha

**Comment by Raulbarossi** [comment]
ao digitar code . em alguma pasta do wsl ele abre o vscode normal no meu windows, mas n sei se é algo configurado ou por padrão ele abriria no host, mas qnd tentei rodar sem ter o chrome no arch do wsl ele avisou e eu instalei com yay antes de chegar a esse ponto

**Comment by Raulbarossi** [comment]
essa questão de tirar o v.2 do undetected pode gerar algum problema?

**Comment by JDaniloC** [comment]
O pyenv não é feito para o windows, é possível instalar ele através do win-pyenv se não me engano, mas realmente não precisa disso. Se você está com dificuldade, instale o windows com o próprio instalador, sem usar o pyenv e asdf. Quanto ao v.2, é por causa do pacote instalado. Mas tem outras variáveis que fazem abrir a janela, como o próprio Chrome instalado, o driver e finalmente o pacote.

**Comment by JDaniloC** [comment]
Inclusive, você instalou o pacote?
`pip install undetected-chromedriver`
Vi que não está no requirements.

**Comment by Raulbarossi** [comment]
> Inclusive, você instalou o pacote? `pip install undetected-chromedriver` Vi que não está no requirements.

**Comment by Raulbarossi** [comment]
> > Inclusive, você instalou o pacote? `pip install undetected-chromedriver` Vi que não está no requirements.

instalei sim, tentei tbm usar .v2 no final, mas n consegui nada nesse modelo, ele pediu pra instalar e acabei caindo nesse comando msm, fechei sem querer, desculpa.

**Comment by Raulbarossi** [comment]
> O pyenv não é feito para o windows, é possível instalar ele através do win-pyenv se não me engano, mas realmente não precisa disso. Se você está com dificuldade, instale o windows com o próprio instalador, sem usar o pyenv e asdf. Quanto ao v.2, é por causa do pacote instalado. Mas tem outras variáveis que fazem abrir a janela, como o próprio Chrome instalado, o driver e finalmente o pacote.

aah entendi, vou ver se consigo uma outra forma de rodar direto e volto pra dizer como foi

**Comment by Raulbarossi** [comment]
agr to encontrando esse problema no windows:
![image](https://github.com/JDaniloC/BetBot/assets/15141367/ac611278-e454-4889-a1cd-68a9c577fb87)
![image](https://github.com/JDaniloC/BetBot/assets/15141367/2e88361c-5aa8-4a36-ac08-9c556c951a3c)

os pacotes já estão instalados e mesmo assim qnd rodo py main.py ele diz q o primeiro já ta faltando

![image](https://github.com/JDaniloC/BetBot/assets/15141367/78f491b5-45e7-4e13-8ae8-5c0645106dbc)

kkkk ta dificil fazer rodar no windows, foi por isso que fui pro WSL
![image](https://github.com/JDaniloC/BetBot/assets/15141367/ad47120a-556f-4a89-b488-f7a2c85570bf)

**Comment by Raulbarossi** [comment]
Consegui rodar, fiz uma limpeza geral em tudo q era python e instalei a versão correta do zero dps de reinicar, subiu lindo tudo agr :D

**Comment by Raulbarossi** [comment]
Obrigado pela atenção e pelo projeto, ta muito foda :D

**Comment by Raulbarossi** [comment]
Obrigado pela atenção e pelo projeto, ta muito foda :D
